// Generated by gencpp from file common_msgs/Controls.msg
// DO NOT EDIT!


#ifndef COMMON_MSGS_MESSAGE_CONTROLS_H
#define COMMON_MSGS_MESSAGE_CONTROLS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace common_msgs
{
template <class ContainerAllocator>
struct Controls_
{
  typedef Controls_<ContainerAllocator> Type;

  Controls_()
    : header()
    , steering(0.0)
    , accelerator(0.0)  {
    }
  Controls_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , steering(0.0)
    , accelerator(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _steering_type;
  _steering_type steering;

   typedef double _accelerator_type;
  _accelerator_type accelerator;





  typedef boost::shared_ptr< ::common_msgs::Controls_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::common_msgs::Controls_<ContainerAllocator> const> ConstPtr;

}; // struct Controls_

typedef ::common_msgs::Controls_<std::allocator<void> > Controls;

typedef boost::shared_ptr< ::common_msgs::Controls > ControlsPtr;
typedef boost::shared_ptr< ::common_msgs::Controls const> ControlsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::common_msgs::Controls_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::common_msgs::Controls_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::common_msgs::Controls_<ContainerAllocator1> & lhs, const ::common_msgs::Controls_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.steering == rhs.steering &&
    lhs.accelerator == rhs.accelerator;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::common_msgs::Controls_<ContainerAllocator1> & lhs, const ::common_msgs::Controls_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace common_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::common_msgs::Controls_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common_msgs::Controls_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common_msgs::Controls_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common_msgs::Controls_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_msgs::Controls_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_msgs::Controls_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::common_msgs::Controls_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cbd78afea6162eac878009c60d81e295";
  }

  static const char* value(const ::common_msgs::Controls_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcbd78afea6162eacULL;
  static const uint64_t static_value2 = 0x878009c60d81e295ULL;
};

template<class ContainerAllocator>
struct DataType< ::common_msgs::Controls_<ContainerAllocator> >
{
  static const char* value()
  {
    return "common_msgs/Controls";
  }

  static const char* value(const ::common_msgs::Controls_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::common_msgs::Controls_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"float64 steering\n"
"float64 accelerator\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::common_msgs::Controls_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::common_msgs::Controls_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.steering);
      stream.next(m.accelerator);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Controls_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::common_msgs::Controls_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::common_msgs::Controls_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "steering: ";
    Printer<double>::stream(s, indent + "  ", v.steering);
    s << indent << "accelerator: ";
    Printer<double>::stream(s, indent + "  ", v.accelerator);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMON_MSGS_MESSAGE_CONTROLS_H
