// Generated by gencpp from file common_msgs/Spawn.msg
// DO NOT EDIT!


#ifndef COMMON_MSGS_MESSAGE_SPAWN_H
#define COMMON_MSGS_MESSAGE_SPAWN_H

#include <ros/service_traits.h>


#include <common_msgs/SpawnRequest.h>
#include <common_msgs/SpawnResponse.h>


namespace common_msgs
{

struct Spawn
{

typedef SpawnRequest Request;
typedef SpawnResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Spawn
} // namespace common_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::common_msgs::Spawn > {
  static const char* value()
  {
    return "0b2d2e872a8e2887d5ed626f2bf2c561";
  }

  static const char* value(const ::common_msgs::Spawn&) { return value(); }
};

template<>
struct DataType< ::common_msgs::Spawn > {
  static const char* value()
  {
    return "common_msgs/Spawn";
  }

  static const char* value(const ::common_msgs::Spawn&) { return value(); }
};


// service_traits::MD5Sum< ::common_msgs::SpawnRequest> should match
// service_traits::MD5Sum< ::common_msgs::Spawn >
template<>
struct MD5Sum< ::common_msgs::SpawnRequest>
{
  static const char* value()
  {
    return MD5Sum< ::common_msgs::Spawn >::value();
  }
  static const char* value(const ::common_msgs::SpawnRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_msgs::SpawnRequest> should match
// service_traits::DataType< ::common_msgs::Spawn >
template<>
struct DataType< ::common_msgs::SpawnRequest>
{
  static const char* value()
  {
    return DataType< ::common_msgs::Spawn >::value();
  }
  static const char* value(const ::common_msgs::SpawnRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::common_msgs::SpawnResponse> should match
// service_traits::MD5Sum< ::common_msgs::Spawn >
template<>
struct MD5Sum< ::common_msgs::SpawnResponse>
{
  static const char* value()
  {
    return MD5Sum< ::common_msgs::Spawn >::value();
  }
  static const char* value(const ::common_msgs::SpawnResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_msgs::SpawnResponse> should match
// service_traits::DataType< ::common_msgs::Spawn >
template<>
struct DataType< ::common_msgs::SpawnResponse>
{
  static const char* value()
  {
    return DataType< ::common_msgs::Spawn >::value();
  }
  static const char* value(const ::common_msgs::SpawnResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMMON_MSGS_MESSAGE_SPAWN_H
