# Topics
topic_route: "route"
topic_map: "perception_map"
topic_pursuit: "pursuit_point"
topic_state: "state"
topic_delaunay: "/delaunay_detector/simplices"
topic_accel: "/accel_control/recta"
frame: 'rslidar'
