# Topics names of planning node
topic_map: 'perception_map'
topic_route: 'route'
topic_simplices: 'simplices'
send_simplices_marker: true

# Hiperparameters of delaunay detector
W_DISTANCE: 1
W_ANGLE: 5
MAX_COST1: 5
MAX_COST2 : -0.75
MAX_DISTANCE: 8

# Parameters of spline aproximation of path
NUM_POINTS: 30
DEGREE: 3
