# Topics names of planning node
topic_perception_map: 'perception_map'
topic_global_map: '/global_map'
topic_route: 'route'
topic_simplices: '/delaunay_detector/simplices'
send_simplices_marker: true

# Hiperparameters of delaunay detector
MAX_DISTANCE: 8
W_DISTANCE: 1
W_ANGLE: 4
W_THRESH: 8
PREV_ANGLE: 0

# Parameters of spline aproximation of path
NUM_POINTS: 10

# Color detection enabled
color_enabled: false
