# Topics names of planning node
topic_map: 'perception_map'
topic_route: 'route'


# Hiperparameters of delaunay detector
W_DISTANCE: 1
W_ANGLE: 8
MAX_COST1: 10
MAX_COST2 : 1
MAX_DISTANCE: 7

# Parameters of spline aproximation of path
NUM_POINTS: 100
DEGREE: 2
